<a href="https://colab.research.google.com/github/himanshusar123/-Machine-Learning-Quiz-Classification-or-Regression-/blob/main/Logistic_regression_Confusion_matrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
# Telecom Customer Churn Prediction Using Logistic Regression
# Project Type

# Classification Problem (Logistic Regression)


# Business Scenario

# A telecom company is losing customers every month.

# Management wants to answer:

# Which customers are likely to leave the company?

# If the company can identify these customers in advance, it can:

# Offer discounts
# Improve customer service
# Increase retention


import pandas as pd

from sklearn.model_selection import train_test_split

from sklearn.linear_model import LogisticRegression

from sklearn.metrics import (
    confusion_matrix,
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    classification_report
)

In [1]:
from google.colab import files

uploaded = files.upload()

Saving Telecom_Customer_Churn_Big_Dataset.csv to Telecom_Customer_Churn_Big_Dataset.csv

In [4]:
df = pd.read_csv(
    "Telecom_Customer_Churn_Big_Dataset.csv"
)

In [5]:
df.head()

,Customer_ID,Age,Monthly_Charges,Tenure_Months,Support_Calls,Internet_Usage_GB,Contract_Type,Churn
0,10001,56,6867,64,1,973,Two-Year,No
1,10002,69,817,33,2,969,Monthly,No
2,10003,46,2896,52,19,749,Yearly,Yes
3,10004,32,2662,14,16,468,Monthly,Yes
4,10005,60,3245,75,19,775,Monthly,Yes

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Customer_ID        2000 non-null   int64
 1   Age                2000 non-null   int64
 2   Monthly_Charges    2000 non-null   int64
 3   Tenure_Months      2000 non-null   int64
 4   Support_Calls      2000 non-null   int64
 5   Internet_Usage_GB  2000 non-null   int64
 6   Contract_Type      2000 non-null   object
 7   Churn              2000 non-null   object
dtypes: int64(6), object(2)
memory usage: 125.1+ KB

In [7]:
df.describe()

,Customer_ID,Age,Monthly_Charges,Tenure_Months,Support_Calls,Internet_Usage_GB
count,2000.000000,2000.000000,2000.00000,2000.000000,2000.00000,2000.000000
mean,11000.500000,46.362500,4238.96200,42.560500,9.75750,524.803000
std,577.494589,16.419924,2187.46664,23.479523,5.72801,275.957934
min,10001.000000,18.000000,501.00000,1.000000,0.00000,50.000000
25%,10500.750000,32.000000,2337.50000,22.000000,5.00000,281.000000
50%,11000.500000,46.500000,4217.50000,43.000000,10.00000,526.000000
75%,11500.250000,61.000000,6175.75000,62.000000,15.00000,765.000000
max,12000.000000,74.000000,7994.00000,83.000000,19.00000,999.000000

In [8]:
df["Churn"].value_counts()

Churn
Yes    1056
No      944
Name: count, dtype: int64

In [9]:
df["Churn"] = df["Churn"].map({
    "No":0,
    "Yes":1
})

In [10]:
X = df[
    [
        "Age",
        "Monthly_Charges",
        "Tenure_Months",
        "Support_Calls"
    ]
]

In [11]:
y = df["Churn"]

In [12]:
X_train,X_test,y_train,y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42
)

In [13]:
model = LogisticRegression()

model.fit(
    X_train,
    y_train
)

LogisticRegression()

In [14]:
y_pred = model.predict(
    X_test
)

In [15]:
accuracy = accuracy_score(
    y_test,
    y_pred
)

print(
    "Accuracy:",
    round(accuracy*100,2),
    "%"
)

Accuracy: 97.5 %

In [16]:
cm = confusion_matrix(
    y_test,
    y_pred
)

print(cm)

[[189   4]
 [  6 201]]

In [17]:
precision = precision_score(
    y_test,
    y_pred
)

print(
    "Precision:",
    round(precision,2)
)

Precision: 0.98

In [18]:
recall = recall_score(
    y_test,
    y_pred
)

print(
    "Recall:",
    round(recall,2)
)

Recall: 0.97

In [19]:
f1 = f1_score(
    y_test,
    y_pred
)

print(
    "F1 Score:",
    round(f1,2)
)

F1 Score: 0.98

In [20]:
print(
    classification_report(
        y_test,
        y_pred
    )
)

              precision    recall  f1-score   support

           0       0.97      0.98      0.97       193
           1       0.98      0.97      0.98       207

    accuracy                           0.97       400
   macro avg       0.97      0.98      0.97       400
weighted avg       0.98      0.97      0.98       400

In [21]:
model.predict_proba(
    [[25,4500,6,12]]
)

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

array([[5.90196045e-04, 9.99409804e-01]])

In [22]:
new_customer = pd.DataFrame({
    "Age":[25],
    "Monthly_Charges":[4500],
    "Tenure_Months":[6],
    "Support_Calls":[12]
})

model.predict_proba(new_customer)

array([[5.90196045e-04, 9.99409804e-01]])

In [23]:
# Age = 45
# Monthly Charges = 1200
# Tenure = 48
# Support Calls = 1

customer_a = pd.DataFrame({
    "Age":[45],
    "Monthly_Charges":[1200],
    "Tenure_Months":[48],
    "Support_Calls":[1]
})

model.predict_proba(customer_a)

array([[1.00000000e+00, 4.07002756e-11]])